version: "3.3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks: 
      - basicFlaskDriver
  redis:
    image: "redis:alpine"
networks: 
  basicFlaskDriver:
    driver: bridge
    driver_opts:
      parent: ens20
