version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks: basicFlaskDriver
    mac_address: 79:19:b0:21:bb:c5
  redis:
    image: "redis:alpine"
networks: 
  basicFlaskDriver:
    driver: macvlan
    driver_opts:
      parent: ens19
